name: test php

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container: hashicorp/terraform:light
    steps:
      - uses: actions/checkout@v4
      - name: version
        run: terraform -v

